### ISSUE TITLE
Add support for large Bloom filters requiring more than 2^32 bits (2^29 bytes) of data

### ISSUE THREAD

**Issue by dferreyra** [mattlorimor/ProbabilisticDataStructures#15]
I had a need for creating a Bloom filter requiring more than 2^32 bits (2^29 bytes) and actually more than 2 GB of memory.  I modified the library to accomplish this for my case.  I'll send a pull request in case you're interested.

**Comment by mattlorimor** [comment]
Taken care of in https://github.com/mattlorimor/ProbabilisticDataStructures/pull/16 by @dferreyra .
